### ISSUE TITLE
No XScreen support?

### ISSUE THREAD

**Issue by ghost** [bbidulock/etwm#2]
Upon launch etwm only runs on XScreen 0.0 rather than the root. CTWM for example runs fine on multiGPU/XScreen setups but ETWM is unusable.

Not sure if you'd count this as a "bug" but recently I've been testing various twm forks/variants and they all work fine on multiGPU/XScreen sets up aside from etwm.

**Comment by bbidulock** [comment]
ETWM was based on a much older version of CTWM with the main purpose of adding EWM/NETWM standards support.  At the time CTWM was basically dead, dying or dormant.  Shortly after adding this support and forking to ETWM, CTWM picked back up and was reborn with a new resurgence of support.  This is likely why it now has XScreen support.  I abandoned ETWM as the new CTWM development team was not open to including the EWM/NETWM improvements in the main CTWM even though they were proposed.  It still sits here solely as an example as to how full EWM/NETWM support could be added to CTWM.

**Comment by ghost** [comment]
Gotcha.
